-- MySQL Script generated by MySQL Workbench
-- Sat May  4 20:17:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema parserlog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `parserlog` ;

-- -----------------------------------------------------
-- Schema parserlog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parserlog` DEFAULT CHARACTER SET utf8 ;
USE `parserlog` ;

-- -----------------------------------------------------
-- Table `parserlog`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parserlog`.`game` (
  `cd_game` INT NOT NULL,
  `nr_total_kill` INT NULL,
  PRIMARY KEY (`cd_game`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parserlog`.`kill_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parserlog`.`kill_type` (
  `cd_kill_type` INT NOT NULL AUTO_INCREMENT,
  `cd_game` INT NOT NULL,
  `nm_kill_type` VARCHAR(50) NOT NULL,
  `nr_kill_type_count` INT NOT NULL,
  PRIMARY KEY (`cd_kill_type`),
  INDEX `fk_kill_type_gamer_idx` (`cd_game` ASC),
  CONSTRAINT `fk_kill_type_gamer`
    FOREIGN KEY (`cd_game`)
    REFERENCES `parserlog`.`game` (`cd_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parserlog`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parserlog`.`player` (
  `cd_player` INT NOT NULL AUTO_INCREMENT,
  `cd_game` INT NOT NULL,
  `nm_player` VARCHAR(50) NOT NULL,
  `nr_player_kill` INT NOT NULL,
  PRIMARY KEY (`cd_player`),
  INDEX `fk_player_game1_idx` (`cd_game` ASC),
  CONSTRAINT `fk_player_game1`
    FOREIGN KEY (`cd_game`)
    REFERENCES `parserlog`.`game` (`cd_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
